language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.9
  - 0.10
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "npm install wru"
  - "sudo apt-get install -qq sqlite3"
  - "sudo apt-get update -qq"
  - "which sqlite3"
  - "sqlite3 --version"
  - "sqlite3 --help"
