language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.9
  - 0.10
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "npm install wru"
  - "PACKAGE=sqlite-shell-linux-x86-3080002; wget http://www.sqlite.org/2013/$PACKAGE.zip"
  - "yes | sudo unzip $PACKAGE -d /usr/bin/"
  - "rm $PACKAGE.zip"
  - "which sqlite3"
  - "sqlite3 --version"
